sudo: required
language: bash
services:
  - docker

env:
  global:
    - secure: CYxBJvXA6aZ6dejDEW3u4/s6yHr0hBScVTKaIOVqBG10XbMgzq1uFz2eMb+/BHxOF5KIkjxT/feulkwYJk1pQTp7OJ8PEf5QaZQkZbsO4+MNPL6tHRGlibCFoQUpKZ/T/LemCX5nW1bPHV5bSofsDZUc/8dmRLLlRu25cgo8cHFf/GVTa1DtnA+wiS3dr8uRGCYbLhN1L/+NoLXNvphA7rzvbbemSpCySAekksTUDkLKsrh4aENzFMy4KAHZf9zwYfM8mSTb5gH8hRe6L4iLuMdtARtugF2LJ8FWfO8/M9ysw+e9d5Uvd6t/DVwE0R8pdKs113PwgMMAufjFkWOr9tIMQ3OzYHO4PtSeZXMzk0hc198lrAzDG/Z+X86dzeVTtI26qNwjLMW/11X+rXeSSQlDk+JXG5NfLuUoopD4KMv7YKpKd8pbP2Ifx1VYzCfaUjadogZBlf7TPTsKvoLD8EEyc++Mfo/pz1YhpDitwkTXbjweLLV29R+5KlRQsyXpJM1+sIrTPP6AcJ4lyMCe3IQlq5gF4oTCW8XXcYpNKCU36Mo/TK+cFQgcYrGn7c+HTiNRf/VV8n1r3diE1eYv9b5lPvIEOMmJh7AaRgrZUk5hXOnTmqROW7Uz2m6wSsxqhk9eIlNn1Vp1EPRSYnIz2tpWHDxCO5B/FWMEjgp/43A=
    - COMMIT_AUTHOR_MAIL: "doc-team@suse.com"
    # If you want to see a list of installed packages in the doc-ci docker container, set to TRUE
    - LIST_PACKAGES=0

before_install:
  - echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST" >> env.list
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH" >> env.list
  - echo "SOURCE_BRANCH=$SOURCE_BRANCH" >> env.list
  - echo "TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG" >> env.list
  - echo "LIST_PACKAGES=$LIST_PACKAGES" >> env.list
  - echo "PUBLISH_PRODUCTS=\"$PUBLISH_PRODUCTS\"" >> env.list
  - echo "ENCRYPTED_PRIVKEY_SECRET=$ENCRYPTED_PRIVKEY_SECRET" >> env.list
  - echo "TRAVIS_COMMIT=$TRAVIS_COMMIT" >> env.list
  - wget https://raw.githubusercontent.com/openSUSE/doc-ci/develop/travis/travis.sh
  - ls
  - echo "Building docker image"
  - docker build -t sle-doc-image .

script:
  - docker run --rm -it sle-doc-image /bin/bash -c '/bin/bash travis.sh'

notifications:
  email:
    on_success: change
    on_failure: always
